#lang racket
(begin (write-byte (char->integer #\h))
       (begin (write-byte (char->integer #\e))
              (begin (write-byte (char->integer #\l))
                     (begin (write-byte (char->integer #\l))
                            (begin (write-byte (char->integer #\o))
                                   (begin (write-byte (char->integer #\ ))
                                          (begin (write-byte (char->integer #\w))
                                                 (begin (write-byte (char->integer #\o))
                                                        (begin (write-byte (char->integer #\r))
                                                               (begin (write-byte (char->integer #\l))
                                                                      (begin (write-byte (char->integer #\d))
                                                                             (begin (write-byte (char->integer #\!))
                                                                                    (write-byte (char->integer #\newline))))))))))))))
