#lang racket
(provide test-runner test-runner-io)
(require rackunit)

(define (test-runner run) 
  ;; Abscond examples
  (check-equal? (run 7) 7)
  (check-equal? (run -8) -8)

  ;; Blackmail examples
  (check-equal? (run '(add1 (add1 7))) 9)
  (check-equal? (run '(add1 (sub1 7))) 7)

  ;; Con examples
  (check-equal? (run '(if (zero? 0) 1 2)) 1)
  (check-equal? (run '(if (zero? 1) 1 2)) 2)
  (check-equal? (run '(if (zero? -7) 1 2)) 2)
  (check-equal? (run '(if (zero? 0)
                          (if (zero? 1) 1 2)
                          7))
                2)
  (check-equal? (run '(if (zero? (if (zero? 0) 1 0))
                          (if (zero? 1) 1 2)
                          7))
                7)

  ;; Dupe examples
  (check-equal? (run #t) #t)
  (check-equal? (run #f) #f)
  (check-equal? (run (if #t 1 2)) 1)
  (check-equal? (run (if #f 1 2)) 2)
  (check-equal? (run (if 0 1 2)) 1)
  (check-equal? (run '(if #t 3 4)) 3)
  (check-equal? (run '(if #f 3 4)) 4)
  (check-equal? (run '(if  0 3 4)) 3)
  (check-equal? (run '(zero? 4)) #f)
  (check-equal? (run '(zero? 0)) #t)  
  ;; Dodger examples
  (check-equal? (run #\a) #\a)
  (check-equal? (run #\b) #\b)
  (check-equal? (run '(char? #\a)) #t)
  (check-equal? (run '(char? #t)) #f)  
  (check-equal? (run '(char? 8)) #f) 
  (check-equal? (run '(char->integer #\a)) (char->integer #\a))
  (check-equal? (run '(integer->char 955)) #\λ)  
  ;; Extort examples
  (check-equal? (run '(add1 #f)) 'err)
  (check-equal? (run '(sub1 #f)) 'err)
  (check-equal? (run '(zero? #f)) 'err)
  (check-equal? (run '(char->integer #f)) 'err)
  (check-equal? (run '(integer->char #f)) 'err)
  (check-equal? (run '(integer->char -1)) 'err)
  (check-equal? (run '(write-byte #f)) 'err)
  (check-equal? (run '(write-byte -1)) 'err)
  (check-equal? (run '(write-byte 256)) 'err)
  ;; Fraud examples
  (check-equal? (run '(let ((x 7)) x)) 7)
  (check-equal? (run '(let ((x 7)) 2)) 2)
  (check-equal? (run '(let ((x 7)) (add1 x))) 8)
  (check-equal? (run '(let ((x (add1 7))) x)) 8)
  (check-equal? (run '(let ((x 7)) (let ((y 2)) x))) 7)
  (check-equal? (run '(let ((x 7)) (let ((x 2)) x))) 2)
  (check-equal? (run '(let ((x 7)) (let ((x (add1 x))) x))) 8)

  (check-equal? (run '(let ((x 0))
                        (if (zero? x) 7 8)))
                7)
  (check-equal? (run '(let ((x 1))
                        (add1 (if (zero? x) 7 8))))
                9)
  (check-equal? (run '(+ 3 4)) 7)
  (check-equal? (run '(- 3 4)) -1)
  (check-equal? (run '(+ (+ 2 1) 4)) 7)
  (check-equal? (run '(+ (+ 2 1) (+ 2 2))) 7)
  (check-equal? (run '(let ((x (+ 1 2)))
                        (let ((z (- 4 x)))
                          (+ (+ x x) z))))
                7)
  ;; Hustle examples  
  (check-equal? (run ''()) '())  
  (check-equal? (run '(box 1)) (box 1))
  (check-equal? (run '(cons 1 2)) (cons 1 2))
  (check-equal? (run '(unbox (box 1))) 1)
  (check-equal? (run '(car (cons 1 2))) 1)
  (check-equal? (run '(cdr (cons 1 2))) 2)
  (check-equal? (run '(cons 1 '())) (list 1))
  (check-equal? (run '(let ((x (cons 1 2)))
                        (begin (cdr x)
                               (car x))))
                1)
  (check-equal? (run '(let ((x (cons 1 2)))
                        (let ((y (box 3)))
                          (unbox y))))
                3)
  
  (check-equal? (run "hello") "hello")
  (check-equal? (run '(string? "hello")) #t)
  (check-equal? (run '(string? #f)) #f)
  (check-equal? (run '(string? (box "hi"))) #f)
  (check-equal? (run '(string-ref "hello" 0)) #\h)
  (check-equal? (run '(string-ref "hello" 1)) #\e)
  (check-equal? (run '(string-ref "hello" 4)) #\o)
  (check-equal? (run '(make-string 3 #\a)) "aaa")
  (check-equal? (run '(string-length "abc")) 3)
  (check-equal? (run '(string-length (make-string 4 #\a))) 4)
  (check-equal? (run '(let ((x "aaa"))
                        (let ((y "bb"))
                          (string-ref y 0))))
                #\b)  
  (check-equal? (run '(let ((x (make-string 3 #\a)))
                        (let ((y (make-string 2 #\b)))
                          x)))
                "aaa")  
  (check-equal? (run '(let ((x (make-string 3 #\a)))
                        (let ((y (make-string 2 #\b)))
                          y)))
                "bb")
  (check-equal? (run '(let ((x "hello"))
                        (begin (string-set! x 4 #\!)
                               x)))
                "hell!")
  (check-equal? (run '(let ((x (make-string 3 #\a)))
                        (let ((y (make-string 2 #\b)))
                          (begin (string-set! x 0 #\!)
                                 x))))
                "!aa")
  (check-equal? (run '(let ((x (make-string 3 #\a)))
                        (let ((y (make-string 2 #\b)))
                          (begin (string-set! y 0 #\!)
                                 y))))
                "!b")

  ;; Iniquity tests
  (check-equal? (run
                 '(begin (define (f x) x)
                         (f 5)))
                5)
  (check-equal? (run
                 '(begin (define (tri x)
                           (if (zero? x)
                               0
                               (+ x (tri (sub1 x)))))
                         (tri 9)))
                45)

  (check-equal? (run
                 '(begin (define (even? x)
                           (if (zero? x)
                               #t
                               (odd? (sub1 x))))
                         (define (odd? x)
                           (if (zero? x)
                               #f
                               (even? (sub1 x))))
                         (even? 101)))
                #f)

  (check-equal? (run
                 '(begin (define (map-add1 xs)
                           (if (empty? xs)
                               '()
                               (cons (add1 (car xs))
                                     (map-add1 (cdr xs)))))
                         (map-add1 (cons 1 (cons 2 (cons 3 '()))))))
                '(2 3 4)))

(define (test-runner-io run)
  ;; Evildoer examples
  (check-equal? (run 7 "") "7\n")
  (check-equal? (run '(write-byte 97) "") "a")
  (check-equal? (run '(read-byte) "a") "97\n")
  (check-equal? (run '(begin (write-byte 97) (read-byte)) "b") "a98\n")
  (check-equal? (run '(read-byte) "") "#<eof>\n")
  (check-equal? (run '(eof-object? (read-byte)) "") "#t\n")
  (check-equal? (run '(eof-object? (read-byte)) "a") "#f\n")
  (check-equal? (run '(begin (write-byte 97) (write-byte 98)) "") "ab")
  ;; Hustle examples
  (check-equal? (run '(let ((x 1))
                        (begin (write-byte 97)
                               1))
                     "")
                "a1\n")

  (check-equal? (run '(let ((x 1))
                        (let ((y 2))
                          (begin (write-byte 97)
                                 1)))
                     "")
                "a1\n")

  ;; corrupts rdi if you don't save it... but how do you observe the problem...
  ;; just starts allocating in some random spot in memory
  (check-equal? (run '(let ((x (cons 1 2)))
                        (begin (write-byte 97)
                               (car x)))
                     "")
                "a1\n"))
