#lang racket
(require rackunit)
(require "../interp-lexical.rkt" "../syntax.rkt")
(define (run p)
  (interp (sexpr->ast p)))
(check-equal? (run 5) 5)
(check-equal? (run '(let ((x 0)) x)) 0)
(check-equal? (run '(let ((x 0)) (let ((y 1)) x))) 0)
(check-equal? (run '(let ((x 0)) (let ((y 1)) y))) 1)
(check-equal? (run '(let ((x 0)) (let ((y x)) y))) 0)
